import { chromium } from "playwright";
const OUT = process.argv[2];
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 950 }, deviceScaleFactor: 2 });
await page.emulateMedia({ reducedMotion: "reduce" });
await page.goto("http://localhost:3000", { waitUntil: "load" });
await page.evaluate(() => document.fonts.ready);
const form = page.locator('[data-node-id="914:1802"]');
await form.scrollIntoViewIfNeeded();
await page.waitForTimeout(500);
await page.fill("#name", "Лада");
await page.type("#phone", "9161234567", { delay: 3 });
await page.type("#messenger", "lada mywish", { delay: 3 });
await page.selectOption("#hall", "Фламинго");
await page.selectOption("#guests", "до 20 человек");
await page.locator("#wish").click();
await page.waitForTimeout(300);
await form.screenshot({ path: `${OUT}/form-final.png` });
await browser.close();
console.log("готово");
